print("Name: Devops, Credit: 3")
print("Name: Software Project Management, Credit: 3")
print("Name: Career Skills for IT Companies, Credit: 3")
print("Name: High Performance Computing, Credit: 4")
print("Name: Capstone Project, Credit: 1")
print("Name: Undergrad Research, Credit: 1")
print("Name: Seminar, Credit: 1")
print("Name: Marketing, Credit: 3")
